### ISSUE TITLE
Indentation is not kept while sending bash commands

### ISSUE THREAD

**Issue by statnmap** [HansKre/markdown-execute#54]
Similar to #51, while passing bash code with indentation in markdown file, indentation is not passed in the Terminal

example md file:

    ```bash
    echo "services:
      caddy:
        image: caddy:alpine
        restart: unless-stopped
        container_name: caddy
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
          - ./certs:/certs
          - ./config:/config
          - ./data:/data
          - ./sites:/srv
        network_mode: "host" " > ~docker-compose.yml
    ```

results in this command sent to the Terminal:

```
user@server:~$ echo "services:
> caddy:
> image: caddy:alpine
> restart: unless-stopped
> container_name: caddy
> volumes:
> - ./Caddyfile:/etc/caddy/Caddyfile
> - ./certs:/certs
> - ./config:/config
> - ./data:/data
> - ./sites:/srv
> network_mode: "host" " > ~docker-compose.yml
```

Thus a yaml file without any spaces:

```yaml
services:
caddy:
image: caddy:alpine
restart: unless-stopped
container_name: caddy
volumes:
- ./Caddyfile:/etc/caddy/Caddyfile
- ./certs:/certs
- ./config:/config
- ./data:/data
- ./sites:/srv
network_mode: host 
```
